name: demo_flutter3_27_4
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  battery_plus: ^4.1.0
  photo_manager: ^3.6.4
  video_player: ^2.8.2
  audioplayers: ^5.2.1
  cached_network_image: ^3.3.1
  file_picker: ^6.1.1
  share_plus: ^7.2.1
  image_picker: ^1.0.7
  path: ^1.8.3
  image_cropper: ^5.0.1
  image_editor: ^1.0.0
  image: ^4.1.3
  video_compress: ^3.1.1
  video_thumbnail: ^0.5.3
  flutter_image_compress: ^2.0.0
  uuid: ^4.2.2
  in_app_purchase: ^3.1.11
  shared_preferences: ^2.2.2
  device_apps: ^2.2.0
  percent_indicator: ^4.2.3
  flutter_contacts_service: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
